name: CICD Pipeline for Model

on:
  push:
    branches:
      - main
    paths:
      - scripts/**
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train the model
      run: python scripts/train_model.py

    - name: Evaluate the model
      run: python scripts/evaluate_model.py

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t andrewdhas/ml-ci-cd-project-fastapi:latest .

    - name: Push Docker image
      run: docker push andrewdhas/ml-ci-cd-project-fastapi:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          docker pull andrewdhas/ml-ci-cd-project-fastapi:latest
          docker stop ml-container || true
          docker rm ml-container || true
          docker run -d --name ml-container -p 8000:8000 andrewdhas/ml-ci-cd-project-fastapi:latest
